server:
    port: 8081

spring:
    main:
        banner-mode: off
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/api_creditos
        username: postgres
        password: lX2uDnCxZAq1
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: false
        show-sql: false
    flyway:
        enabled: true
        baseline-on-migrate: true
        baseline-version: 0
    kafka:
        bootstrap-servers: localhost:9092,host.docker.internal:9092
topicos:
  creditos:
    request:
      topic: "creditos.request.topic.v1"